<?php 

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use App\Models\BookModel;

class BookFabricatorSeeder extends Seeder
{
    public function run()
    {
        $bookModel = new BookModel();

        $data = [
            [
                'slug' => '1',
                'title' => 'Muslimah Impian (Belajar, Berprestasi, dan Bermanfaat)',
                'author' => 'Aisyah Utami, Masruroh Samir, Adella Kusuma',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786230051159',
                'year' => '2023',
                'rack_id' => '1',
                'category_id' => '1',
                'book_cover' => 'book-1.jpg',
            ],
            [
                'slug' => '2',
                'title' => 'Melihat Allah : Ngaji Kitab Roaitullah Bersama Buya Syakur Yasin',
                'author' => 'K.H. Buya Syakur Yasin, M.A., K.H. BUYA SYAKUR YASIN',
                'publisher' => 'Yrama Media',
                'isbn' => '9786023825615',
                'year' => '28 Sep 2023',
                'rack_id' => '2',
                'category_id' => '1',
                'book_cover' => 'book-2.jpg',
            ],
            [
                'slug' => '3',
                'title' => 'Keajaiban Shalat dan Sabar',
                'author' => 'Ahmad Zacky El-Syafa, AHMAD ZAKCY EL-SYAFA',
                'publisher' => 'Srikandi Empat Widya Utama',
                'isbn' => '9786023825622',
                'year' => '26 Okt 2023',
                'rack_id' => '3',
                'category_id' => '1',
                'book_cover' => 'book-3.jpg',
            ],
            [
                'slug' => '4',
                'title' => 'Jangan Takut Bicara Masa Depan',
                'author' => 'Yul Rachmawati',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786230036941',
                'year' => '13 Des 2023',
                'rack_id' => '4',
                'category_id' => '1',
                'book_cover' => 'book-4.jpg',
            ],
            [
                'slug' => '5',
                'title' => '50 Rahasia Menjadi Wanita Salihah',
                'author' => 'ARUM FAIZA, ARUM FAIZA',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786230051050',
                'year' => '28 Nov 2023',
                'rack_id' => '5',
                'category_id' => '1',
                'book_cover' => 'book-5.jpg',
            ],
            [
                'slug' => '6',
                'title' => 'Rahasia Sukses Budidaya Ikan Patin Secara Intensif',
                'author' => 'Hadi Tribowo',
                'publisher' => 'Nuansa Aulia',
                'isbn' => '9789790713680',
                'year' => '8 Nov 2023',
                'rack_id' => '6',
                'category_id' => '2',
                'book_cover' => 'book-6.jpg',
            ],
            [
                'slug' => '7',
                'title' => 'Rahasia Sukses Budi Daya Burung Walet',
                'author' => 'Hadi Tribowo',
                'publisher' => 'Nuansa Aulia',
                'isbn' => '9789790713659',
                'year' => '2 Agt 2023',
                'rack_id' => '7',
                'category_id' => '2',
                'book_cover' => 'book-7.jpg',
            ],
            [
                'slug' => '8',
                'title' => 'Bahasa Indonesia untuk Perguruan Tinggi',
                'author' => 'Toyidin',
                'publisher' => 'Yrama Widya',
                'isbn' => '9786232058910',
                'year' => '8 Nov 2023',
                'rack_id' => '8',
                'category_id' => '3',
                'book_cover' => 'book-8.jpg',
            ],
            [
                'slug' => '9',
                'title' => 'Beropinilah!: Mengembangkan Proses Kreatif Menulis Opini',
                'author' => 'PEPIH NUGRAHA',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786230051173',
                'year' => '9 Nov 2023',
                'rack_id' => '9',
                'category_id' => '3',
                'book_cover' => 'book-9.jpg',
            ],
            [
                'slug' => '10',
                'title' => 'Jurnalisme Dasar',
                'author' => 'Luwi Iswara',
                'publisher' => 'Penerbit Buku Kompas',
                'isbn' => '9789797095420',
                'year' => '24 Okt 2023',
                'rack_id' => '10',
                'category_id' => '3',
                'book_cover' => 'book-10.jpg',
            ],
            [
                'slug' => '11',
                'title' => 'Berani Berdebat : Sukses Debat Tanpa Ngegas',
                'author' => 'Anna Mutmainnah',
                'publisher' => 'Anak Hebat Indonesia',
                'isbn' => '9786231640178',
                'year' => '4 Okt 2023',
                'rack_id' => '1',
                'category_id' => '3',
                'book_cover' => 'book-11.jpg',
            ],
            [
                'slug' => '12',
                'title' => 'Metodologi Penelitian Kesehatan Edisi Terbaru',
                'author' => 'I Ketut Swarjana, S.K.M., M.P.H., Dr.P.H.',
                'publisher' => 'Andi',
                'isbn' => '9786230135019',
                'year' => '27 Agt 2023',
                'rack_id' => '2',
                'category_id' => '3',
                'book_cover' => 'book-12.jpg',
            ],
            [
                'slug' => '13',
                'title' => 'Membangun Peradaban Dunia',
                'author' => 'UNTUNG WIDYANTO, DKK.',
                'publisher' => 'Penerbit Buku Kompas',
                'isbn' => '9786233468909',
                'year' => '4 Jul 2023',
                'rack_id' => '3',
                'category_id' => '4',
                'book_cover' => 'book-13.jpg',
            ],
            [
                'slug' => '14',
                'title' => 'Struktur Beton Bertulang Tahan Gempa',
                'author' => 'Anugrah Pamungkas',
                'publisher' => 'Andi Offset',
                'isbn' => '9789792965957',
                'year' => '30 Sep 2018',
                'rack_id' => '4',
                'category_id' => '4',
                'book_cover' => 'book-14.jpg',
            ],
            [
                'slug' => '15',
                'title' => '36 Desain Rumah Kost Pilihan',
                'author' => 'Jaka Nur Sukma',
                'publisher' => 'Puspa Swara',
                'isbn' => '9786022160250',
                'year' => '30 Mei 2016',
                'rack_id' => '5',
                'category_id' => '4',
                'book_cover' => 'book-15.jpg',
            ],
            [
                'slug' => '16',
                'title' => '10 Desain Ruang Bawah Atap',
                'author' => 'Andie Arif Wicaksono, Ahmad Kaukabudin, Angga Setyawan',
                'publisher' => 'Griya Kreasi',
                'isbn' => '9786026564450',
                'year' => '30 Okt 2019',
                'rack_id' => '6',
                'category_id' => '4',
                'book_cover' => 'book-16.jpg',
            ],
            [
                'slug' => '17',
                'title' => 'Seni Rupa Modern Edisi Revisi',
                'author' => 'Dharsono Sony Kartika',
                'publisher' => 'Rekayasa Sains',
                'isbn' => '9789793784816',
                'year' => '27 Jan 2017',
                'rack_id' => '7',
                'category_id' => '4',
                'book_cover' => 'book-17.jpg',
            ],
            [
                'slug' => '18',
                'title' => 'Keterampilan Membatik untuk Anak',
                'author' => 'Nurbertus Ka',
                'publisher' => 'Arcita',
                'isbn' => '9786027849228',
                'year' => '2013',
                'rack_id' => '8',
                'category_id' => '5',
                'book_cover' => 'book-18.jpg',
            ],
            [
                'slug' => '19',
                'title' => 'Panduan Praktis Budidaya Kakao',
                'author' => 'TUMPAL H.S.SIREGAR',
                'publisher' => 'PENEBAR SWADAYA',
                'isbn' => '9786232251229',
                'year' => '22 Okt 2021',
                'rack_id' => '9',
                'category_id' => '6',
                'book_cover' => 'book-19.jpg',
            ],
            [
                'slug' => '20',
                'title' => 'Manajemen Perubahan: Membalik Arah Menuju Usaha Perkebunan yang Tangguh Melalui Strategi Optimalisasi Efisiensi',
                'author' => 'Akmaluddin Hasibuan',
                'publisher' => 'Andi Offset',
                'isbn' => '9789792931402',
                'year' => '',
                'rack_id' => '10',
                'category_id' => '6',
                'book_cover' => 'book-20.jpg',
            ],
            [
                'slug' => '21',
                'title' => 'Panduan Berkebun Kopi',
                'author' => 'PUDJI R',
                'publisher' => 'Penebar Swadaya',
                'isbn' => '9786232251236',
                'year' => '22 Okt 2021',
                'rack_id' => '1',
                'category_id' => '6',
                'book_cover' => 'book-21.jpg',
            ],
            [
                'slug' => '22',
                'title' => 'Panduan Budidaya Kelapa Sawit untuk Pekebun',
                'author' => 'Iyung Pahan',
                'publisher' => 'PENEBAR SWADAYA',
                'isbn' => '9786232251182',
                'year' => '22 Okt 2021',
                'rack_id' => '2',
                'category_id' => '6',
                'book_cover' => 'book-22.jpg',
            ],
            [
                'slug' => '23',
                'title' => 'Budidaya Kelapa Sawit Seri 1',
                'author' => 'MEMET HAKIM, MARULI PARDAMEAN, ATEP YULIANTO I',
                'publisher' => 'Intimedia',
                'isbn' => '9786021507957',
                'year' => '28 Okt 2019',
                'rack_id' => '3',
                'category_id' => '6',
                'book_cover' => 'book-23.jpg',
            ],
            [
                'slug' => '24',
                'title' => '(Bukan) Kisah Sukses Erick Thohir',
                'author' => 'Abdullah Sammy',
                'publisher' => 'pbk',
                'isbn' => '9786233467001',
                'year' => '26 Nov 2022',
                'rack_id' => '4',
                'category_id' => '7',
                'book_cover' => 'book-24.jpg',
            ],
            [
                'slug' => '25',
                'title' => 'Seri TEMPO Ali Sadikin',
                'author' => 'TEMPO',
                'publisher' => 'Kepustakaan Populer Gramedia',
                'isbn' => '9786231341167',
                'year' => '5 Nov 2023',
                'rack_id' => '5',
                'category_id' => '7',
                'book_cover' => 'book-25.jpg',
            ],
            [
                'slug' => '26',
                'title' => 'The Brilliant Exporter: Kisah Inspiratif Basuki Kurniawan',
                'author' => 'Zulfikar Fuad',
                'publisher' => 'Gramedia Pustaka Utama',
                'isbn' => '9786020656373',
                'year' => '19 Okt 2023',
                'rack_id' => '6',
                'category_id' => '7',
                'book_cover' => 'book-26.jpg',
            ],
            [
                'slug' => '27',
                'title' => 'Beyond The Story : 10-Year Record Of BTS',
                'author' => 'Myeongseok Kang & BTS',
                'publisher' => 'Transmedia Pustaka',
                'isbn' => '9786238216079',
                'year' => '10 Agt 2023',
                'rack_id' => '7',
                'category_id' => '7',
                'book_cover' => 'book-27.jpg',
            ],
            [
                'slug' => '28',
                'title' => 'Amr Bin Ash',
                'author' => 'Dr. Mahmud Syalabi',
                'publisher' => 'Alvabet',
                'isbn' => '9786232201668',
                'year' => '6 Nov 2023',
                'rack_id' => '8',
                'category_id' => '7',
                'book_cover' => 'book-28.jpg',
            ],
            [
                'slug' => '29',
                'title' => 'Indonesia Pusat Gravitasi Industri Baterai Dunia',
                'author' => 'Cyrillus Harinowo dkk',
                'publisher' => 'Gramedia Pustaka Utama',
                'isbn' => '9786020671635',
                'year' => '9 Sep 2023',
                'rack_id' => '9',
                'category_id' => '8',
                'book_cover' => 'book-29.jpg',
            ],
            [
                'slug' => '30',
                'title' => 'Pasar Valuta Asing: Meraup Cuan Jangka Panjang',
                'author' => 'Meta Setyani',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786230033407',
                'year' => '19 Jun 2022',
                'rack_id' => '10',
                'category_id' => '8',
                'book_cover' => 'book-30.jpg',
            ],
            [
                'slug' => '31',
                'title' => 'Bernalar Sebelum Klik',
                'author' => 'Agus Sudibyo',
                'publisher' => 'Gramedia Pustaka Utama',
                'isbn' => '',
                'year' => '2023',
                'rack_id' => '1',
                'category_id' => '8',
                'book_cover' => 'book-31.jpg',
            ],
            [
                'slug' => '32',
                'title' => 'Cuan Trading Pakai Fibonacci',
                'author' => 'Catherine Wiliam',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786230033551',
                'year' => '19 Jun 2022',
                'rack_id' => '2',
                'category_id' => '8',
                'book_cover' => 'book-32.jpg',
            ],
            [
                'slug' => '33',
                'title' => 'THE INVINCIBLE COMPANY (Strategyzer Series: Business Model Generation, dll)',
                'author' => 'Alex Osterwalder, Yves Pigneur, Greg Bernada, Alan Smith',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786230036989',
                'year' => '6 Jan 2023',
                'rack_id' => '3',
                'category_id' => '8',
                'book_cover' => 'book-33.jpg',
            ],
            [
                'slug' => '34',
                'title' => 'Ekspresi Tuban',
                'author' => 'Fajar Ciptandi',
                'publisher' => 'Gramedia Pustaka Utama',
                'isbn' => '9786020664705',
                'year' => '5 Des 2022',
                'rack_id' => '4',
                'category_id' => '9',
                'book_cover' => 'book-34.jpg',
            ],
            [
                'slug' => '35',
                'title' => 'Experimental Design And Data Analysis Using R',
                'author' => 'IR. AKHMAD DAKHLAN, M.P., PH.D.',
                'publisher' => 'Gramedia Pustaka Utama',
                'isbn' => '9786025966187',
                'year' => '',
                'rack_id' => '5',
                'category_id' => '9',
                'book_cover' => 'book-35.jpg',
            ],
            [
                'slug' => '36',
                'title' => 'Pengantar Sejarah dan Konsep Estetika',
                'author' => 'Lingga Agung',
                'publisher' => 'Kanisius',
                'isbn' => '9789792153408',
                'year' => '19 Desember 2017',
                'rack_id' => '6',
                'category_id' => '9',
                'book_cover' => 'book-36.jpg',
            ],
            [
                'slug' => '37',
                'title' => 'Desain Rumah Wisata Nusantara',
                'author' => 'Sayembara Desain Rumah Wisata',
                'publisher' => 'Imaji',
                'isbn' => '9786029260366',
                'year' => '26 Jul 2017',
                'rack_id' => '7',
                'category_id' => '9',
                'book_cover' => 'book-37.jpg',
            ],
            [
                'slug' => '38',
                'title' => 'The Power of Coreldraw',
                'author' => 'Arista Prasetyo Adi',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => 'SCOOPG173703',
                'year' => '17 Mar 2019',
                'rack_id' => '8',
                'category_id' => '9',
                'book_cover' => 'book-38.jpg',
            ],
            [
                'slug' => '39',
                'title' => 'Dallergut 2 : Toko Penjual Mimpi',
                'author' => 'Lee Miye',
                'publisher' => 'Baca',
                'isbn' => '9786026486738',
                'year' => '26 Jan 2023',
                'rack_id' => '9',
                'category_id' => '10',
                'book_cover' => 'book-39.jpg',
            ],
            [
                'slug' => '40',
                'title' => 'The Ballad of Never After',
                'author' => 'Stephanie Garber',
                'publisher' => 'Mizan Publishing',
                'isbn' => '9786232423558',
                'year' => '16 Mei 2023',
                'rack_id' => '10',
                'category_id' => '10',
                'book_cover' => 'book-40.jpg',
            ],
            [
                'slug' => '41',
                'title' => 'The Dark Tower #2: The Drawing of the Three (Penarikan Tiga Unsur)',
                'author' => 'Stephen King',
                'publisher' => 'Gramedia Pustaka Utama',
                'isbn' => '9786020372006',
                'year' => '21 Agt 2017',
                'rack_id' => '1',
                'category_id' => '10',
                'book_cover' => 'book-41.jpg',
            ],
            [
                'slug' => '42',
                'title' => 'Creepy Case Club 1: Kasus Nyanyian Berhantu',
                'author' => 'Rizal Iwan',
                'publisher' => 'Kepustakaan Populer Gramedia',
                'isbn' => '9786024810061',
                'year' => '26 Nov 2023',
                'rack_id' => '2',
                'category_id' => '10',
                'book_cover' => 'book-42.jpg',
            ],
            [
                'slug' => '43',
                'title' => 'Creepy Case Club 6: Kasus Hantu Panggung',
                'author' => 'Rizal Iwan',
                'publisher' => 'Kepustakaan Populer Gramedia',
                'isbn' => '9786231341211',
                'year' => '26 Nov 2023',
                'rack_id' => '3',
                'category_id' => '10',
                'book_cover' => 'book-43.jpg',
            ],
            [
                'slug' => '44',
                'title' => 'Buku Seri Ensiklopedia Lift The Flap: Tubuh Manusia',
                'author' => 'Igloobooks',
                'publisher' => 'Bhuana Ilmu Populer',
                'isbn' => '9786230407864',
                'year' => '28 Nov 2022',
                'rack_id' => '4',
                'category_id' => '11',
                'book_cover' => 'book-44.jpg',
            ],
            [
                'slug' => '45',
                'title' => 'Petualangan Tintin: Bintang Misterius',
                'author' => 'Herge',
                'publisher' => 'Gramedia Pustaka Utama',
                'isbn' => '9786020308371',
                'year' => '28 Agt 2014',
                'rack_id' => '5',
                'category_id' => '11',
                'book_cover' => 'book-45.jpg',
            ],
            [
                'slug' => '46',
                'title' => 'Opredo 2in1 Poster Hafiz Hafizah - Belajar Membaca',
                'author' => 'PT Hidayah Insan Mulia',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '722120426',
                'year' => '9 Jul 2022',
                'rack_id' => '6',
                'category_id' => '11',
                'book_cover' => 'book-46.jpg',
            ],
            [
                'slug' => '47',
                'title' => 'Disney Baby Kata Pertamaku (Bilingual Book)',
                'author' => 'Igloobooks',
                'publisher' => 'Bhuana Ilmu Populer',
                'isbn' => '9786230414152',
                'year' => '29 Nov 2023',
                'rack_id' => '7',
                'category_id' => '11',
                'book_cover' => 'book-47.jpg',
            ],
            [
                'slug' => '48',
                'title' => 'Bedtime Stories Disney: Cinderella',
                'author' => 'Igloobooks',
                'publisher' => 'Bhuana Ilmu Populer',
                'isbn' => '9786230413551',
                'year' => '29 Nov 2023',
                'rack_id' => '8',
                'category_id' => '11',
                'book_cover' => 'book-48.jpg',
            ],
            [
                'slug' => '49',
                'title' => 'Mariposa',
                'author' => 'Luluk HF',
                'publisher' => 'Coconut Books',
                'isbn' => '9786025508615',
                'year' => '19 Mar 2020',
                'rack_id' => '9',
                'category_id' => '12',
                'book_cover' => 'book-49.jpg',
            ],
            [
                'slug' => '50',
                'title' => "TeenLit: Vio Don't Mess Up",
                'author' => 'Shania Kurniawan',
                'publisher' => 'Gramedia Pustaka Utama',
                'isbn' => '9786020627847',
                'year' => '13 Mei 2019',
                'rack_id' => '10',
                'category_id' => '12',
                'book_cover' => 'book-50.jpg',
            ],
            [
                'slug' => '51',
                'title' => 'Lipstick: A Blackpink Story',
                'author' => 'Inkarnadine',
                'publisher' => 'Bukune',
                'isbn' => '9786022202899',
                'year' => '30 Okt 2018',
                'rack_id' => '1',
                'category_id' => '12',
                'book_cover' => 'book-51.jpg',
            ],
            [
                'slug' => '52',
                'title' => 'Jeda dan Spasi',
                'author' => 'Nisa Rahmah',
                'publisher' => 'Falcon Publishing',
                'isbn' => '9786026714350',
                'year' => '21 Okt 2018',
                'rack_id' => '2',
                'category_id' => '12',
                'book_cover' => 'book-52.jpg',
            ],
            [
                'slug' => '53',
                'title' => 'Outwit',
                'author' => 'Erlita Scorpio',
                'publisher' => 'Aksara Plus',
                'isbn' => '9786025884085',
                'year' => '5 Sep 2018',
                'rack_id' => '3',
                'category_id' => '12',
                'book_cover' => 'book-53.jpg',
            ],
            [
                'slug' => '54',
                'title' => 'Firasat',
                'author' => 'Dr. Ibrahim Elfiky',
                'publisher' => 'Qantara',
                'isbn' => '9786238870509',
                'year' => '6 Nov 2023',
                'rack_id' => '4',
                'category_id' => '13',
                'book_cover' => 'book-54.jpg',
            ],
            [
                'slug' => '55',
                'title' => 'Filosofi Teras (New Cover)',
                'author' => 'HENRY MANAMPIRING',
                'publisher' => 'Penerbit Buku Kompas',
                'isbn' => '9786233469319',
                'year' => '21 Nov 2023',
                'rack_id' => '5',
                'category_id' => '13',
                'book_cover' => 'book-55.jpg',
            ],
            [
                'slug' => '56',
                'title' => 'Filsafat Politik: Apa Dan Bagaimana',
                'author' => 'Jonathan Floyd',
                'publisher' => 'Gramedia Pustaka Utama',
                'isbn' => '9786020673097',
                'year' => '17 Sep 2023',
                'rack_id' => '6',
                'category_id' => '13',
                'book_cover' => 'book-56.jpg',
            ],
            [
                'slug' => '57',
                'title' => 'Filsafat Untuk Pemalas',
                'author' => 'ACH. DHOFIR ZUHRY',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786230049880',
                'year' => '7 Sep 2023',
                'rack_id' => '7',
                'category_id' => '13',
                'book_cover' => 'book-57.jpg',
            ],
            [
                'slug' => '58',
                'title' => 'Filosofi Teras',
                'author' => 'Henry Manampiring',
                'publisher' => 'Penerbit Buku Kompas',
                'isbn' => '582312136',
                'year' => '20 Jul 2023',
                'rack_id' => '8',
                'category_id' => '13',
                'book_cover' => 'book-58.jpg',
            ],
            [
                'slug' => '59',
                'title' => 'Album Kenangan Eros dan Reformasi (2023)',
                'author' => 'Erik Prasetya',
                'publisher' => 'Kepustakaan Populer Gramedia',
                'isbn' => '9786024811167',
                'year' => '22 Agt 2023',
                'rack_id' => '9',
                'category_id' => '14',
                'book_cover' => 'book-59.jpg',
            ],
            [
                'slug' => '60',
                'title' => 'SPORTSCAPES',
                'author' => 'Kompas',
                'publisher' => 'Penerbit Buku Kompas',
                'isbn' => '9786024124342',
                'year' => '31 Jul 2018',
                'rack_id' => '10',
                'category_id' => '14',
                'book_cover' => 'book-60.jpg',
            ],
            [
                'slug' => '61',
                'title' => 'Proteksi Sistem Tenaga Listrik',
                'author' => 'Ir. Harnoko S., M.T. & Ir. Sri Lestari, M.T.',
                'publisher' => 'Andi',
                'isbn' => '9786230130083',
                'year' => '24 Nov 2022',
                'rack_id' => '1',
                'category_id' => '14',
                'book_cover' => 'book-61.jpg',
            ],
            [
                'slug' => '62',
                'title' => 'National Geographic: Mesir Kuno',
                'author' => 'Jill Rubalcaba',
                'publisher' => 'Kepustakaan Populer Gramedia',
                'isbn' => '9786024247812',
                'year' => '4 Feb 2018',
                'rack_id' => '2',
                'category_id' => '14',
                'book_cover' => 'book-62.jpg',
            ],
            [
                'slug' => '63',
                'title' => 'Modal Ngeblog Bisa Sampai Yurop',
                'author' => 'Haryadi Yansyah',
                'publisher' => 'Laksana',
                'isbn' => '9786024077419',
                'year' => '28 Jun 2020',
                'rack_id' => '4',
                'category_id' => '14',
                'book_cover' => 'book-63.jpg',
            ],
            [
                'slug' => '64',
                'title' => 'Gunting, Warnai, Tempel 2D dan 3D: Unicorn & Peri',
                'author' => 'Veronica Winata, VERONICA WINATA',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786230051197',
                'year' => '21 Nov 2023',
                'rack_id' => '5',
                'category_id' => '15',
                'book_cover' => 'book-64.jpg',
            ],
            [
                'slug' => '65',
                'title' => 'Gunting, Warnai, Tempel 2D dan 3D: Dinosaurus',
                'author' => 'Veronica Winata, VERONICA WINATA',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786230051180',
                'year' => '21 Nov 2023',
                'rack_id' => '6',
                'category_id' => '15',
                'book_cover' => 'book-65.jpg',
            ],
            [
                'slug' => '66',
                'title' => 'Mewarnai & Fakta Sains: Dinosaurus + Stiker',
                'author' => 'KOEN SETYAWAN, KOEN SETYAWAN',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786230051210',
                'year' => '28 Nov 2023',
                'rack_id' => '7',
                'category_id' => '15',
                'book_cover' => 'book-66.jpg',
            ],
            [
                'slug' => '67',
                'title' => 'Cocomelon: Buku Mewarnai Super Besar Imut dan Lucu',
                'author' => 'MOONBUG ENTERTAINMENT',
                'publisher' => 'Gramedia Pustaka Utama',
                'isbn' => '9786020673561',
                'year' => '19 Nov 2023',
                'rack_id' => '8',
                'category_id' => '15',
                'book_cover' => 'book-67.jpg',
            ],
            [
                'slug' => '68',
                'title' => 'Cocomelon: Buku Stiker Seru - 200+ stiker',
                'author' => 'MOONBUG ENTERTAINMENT',
                'publisher' => 'Gramedia Pustaka Utama',
                'isbn' => '9786020673578',
                'year' => '19 Nov 2023',
                'rack_id' => '9',
                'category_id' => '15',
                'book_cover' => 'book-68.jpg',
            ],
            [
                'slug' => '69',
                'title' => 'Negara Kesejahteraan Ala Anies Baswedan',
                'author' => 'Sukron Kamil, Setyadi Sulaiman, Arief Rahman Hakim, Endi Aulia Garadian',
                'publisher' => 'Kaki Langit Kencana',
                'isbn' => '9786025848490',
                'year' => '1 Sep 2023',
                'rack_id' => '10',
                'category_id' => '16',
                'book_cover' => 'book-69.jpg',
            ],
            [
                'slug' => '70',
                'title' => 'Refleksi Pemikiran Hukum Tata Negara',
                'author' => 'Umbu Rauta',
                'publisher' => 'RajaGrafindo Persada',
                'isbn' => '9786230802614',
                'year' => '19 Okt 2023',
                'rack_id' => '1',
                'category_id' => '16',
                'book_cover' => 'book-70.jpg',
            ],
            [
                'slug' => '71',
                'title' => 'Antropologi Hukum Kontemporer',
                'author' => 'Dr. Erdianto Effendi, S.H., M.Hum.',
                'publisher' => 'RajaGrafindo Persada',
                'isbn' => '9786230803369',
                'year' => '19 Okt 2023',
                'rack_id' => '2',
                'category_id' => '16',
                'book_cover' => 'book-71.jpg',
            ],
            [
                'slug' => '72',
                'title' => 'Restorative Justice',
                'author' => 'Jean Calvijn Simanjuntak',
                'publisher' => 'RajaGrafindo Persada',
                'isbn' => '9786230802751',
                'year' => '19 Nov 2023',
                'rack_id' => '3',
                'category_id' => '16',
                'book_cover' => 'book-72.jpg',
            ],
            [
                'slug' => '73',
                'title' => 'Pengantar Kode Etik Notaris: Indonesia, Amerika Serikat, Italia, dan Kanada',
                'author' => 'Prof.Dr.H.Salim HS.,S.H.,M.S.',
                'publisher' => 'Prc Pustaka Reka Cipta',
                'isbn' => '9786021311677',
                'year' => '9 Mar 2022',
                'rack_id' => '4',
                'category_id' => '16',
                'book_cover' => 'book-73.jpg',
            ],
            [
                'slug' => '74',
                'title' => 'Poligami Bola Murtad Duologi 1 | Kumpulan Revisi Kolom Bahasa Harian Kompas',
                'author' => 'SAMSUDIN BERLIAN',
                'publisher' => 'Penerbit Buku Kompas',
                'isbn' => '9786231600790',
                'year' => '18 Nov 2023',
                'rack_id' => '5',
                'category_id' => '17',
                'book_cover' => 'book-74.jpg',
            ],
            [
                'slug' => '75',
                'title' => 'Poligami Bola Murtad Duologi 2 | Kumpulan Revisi Kolom Bahasa Harian Kompas',
                'author' => 'SAMSUDIN BERLIAN',
                'publisher' => 'Penerbit Buku Kompas',
                'isbn' => '9786231600813',
                'year' => '18 Nov 2023',
                'rack_id' => '6',
                'category_id' => '17',
                'book_cover' => 'book-75.jpg',
            ],
            [
                'slug' => '76',
                'title' => '#Bincang Akhlak',
                'author' => 'Takdir Alisyahbana Ridwan',
                'publisher' => 'Media Kita',
                'isbn' => '9789797947873',
                'year' => '10 Okt 2023',
                'rack_id' => '7',
                'category_id' => '17',
                'book_cover' => 'book-76.jpg',
            ],
            [
                'slug' => '77',
                'title' => 'Komik Pesantren Keren Reborn El Sudah Gede',
                'author' => 'Tethy Ezokanzo, Dkk',
                'publisher' => 'pustaka al-kautsar kids',
                'isbn' => '9786235338194',
                'year' => '11 Agt 2023',
                'rack_id' => '8',
                'category_id' => '17',
                'book_cover' => 'book-77.jpg',
            ],
            [
                'slug' => '78',
                'title' => 'Series Komik Pesantren Keren',
                'author' => 'Tethy Ezokanzo, Dkk',
                'publisher' => 'pustaka al-kautsar kids',
                'isbn' => '5920320230022',
                'year' => '26 Agt 2023',
                'rack_id' => '9',
                'category_id' => '17',
                'book_cover' => 'book-78.jpg',
            ],
            [
                'slug' => '79',
                'title' => 'Insuredemic : Jejak Digital Jerit Derita Nasabah',
                'author' => 'Irvan Rahardjo',
                'publisher' => 'Pt Kaya Ilmu Bermanfaat',
                'isbn' => '9786239785277',
                'year' => '14 Des 2021',
                'rack_id' => '10',
                'category_id' => '18',
                'book_cover' => 'book-79.jpg',
            ],
            [
                'slug' => '80',
                'title' => 'Perilaku Organisasi',
                'author' => 'Alexander Hery, S.E., M.Si.',
                'publisher' => 'Papas Sinar Sinanti',
                'isbn' => '9786021374832',
                'year' => '18 Okt 2023',
                'rack_id' => '1',
                'category_id' => '18',
                'book_cover' => 'book-80.jpg',
            ],
            [
                'slug' => '81',
                'title' => 'Modernisasi Pertanian dan Pembangunan Pedesaan di Tiongkok',
                'author' => 'Kong Xiangzhi',
                'publisher' => 'Pustaka Obor Indonesia',
                'isbn' => '9786236421642',
                'year' => '22 Agt 2016',
                'rack_id' => '2',
                'category_id' => '18',
                'book_cover' => 'book-81.jpg',
            ],
            [
                'slug' => '82',
                'title' => "'Manusia Baru' Indonesia",
                'author' => 'RHOMA DWI ARIA YULIANTRI',
                'publisher' => 'Penerbit Buku Kompas',
                'isbn' => '9786233469074',
                'year' => '18 Okt 2023',
                'rack_id' => '3',
                'category_id' => '18',
                'book_cover' => 'book-82.jpg',
            ],
            [
                'slug' => '83',
                'title' => 'Pemindahan Ibu Kota Negara',
                'author' => 'Dr. K.P. Suharyono Soemarwoto Hadiningrat, M.M.',
                'publisher' => 'Penerbit Buku Kompas',
                'isbn' => '9786233467025',
                'year' => '24 Okt 2023',
                'rack_id' => '4',
                'category_id' => '18',
                'book_cover' => 'book-83.jpg',
            ],
            [
                'slug' => '84',
                'title' => 'The Happiest Kids',
                'author' => 'Rina Mae Acosta & Michele Hutchison, RINA MAE ACOSTA',
                'publisher' => 'Rene Book',
                'isbn' => '9786236083659',
                'year' => '23 Nov 2023',
                'rack_id' => '5',
                'category_id' => '19',
                'book_cover' => 'book-84.jpg',
            ],
            [
                'slug' => '85',
                'title' => 'Aku ingin Tahu Tentang: Makanan',
                'author' => 'Usborne',
                'publisher' => 'Bhuana Ilmu Populer',
                'isbn' => '9786024554934',
                'year' => '22 Apr 2018',
                'rack_id' => '6',
                'category_id' => '19',
                'book_cover' => 'book-85.jpg',
            ],
            [
                'slug' => '86',
                'title' => 'Nama-Nama Bayi Islami Terpopuler dan Bermakna Indah',
                'author' => 'Zuhra Nur Fadhilah, Muhammad Iqbal Zulfikar',
                'publisher' => 'Anak Hebat Indonesia',
                'isbn' => '9786234007671',
                'year' => '7 Nov 2023',
                'rack_id' => '7',
                'category_id' => '19',
                'book_cover' => 'book-86.jpg',
            ],
            [
                'slug' => '87',
                'title' => 'Teladan Kebahagiaan dari Rumah Tangga Kenabian',
                'author' => 'Ahmad Husain Fahasbu',
                'publisher' => 'Diva Press',
                'isbn' => '9786231892645',
                'year' => '5 Nov 2023',
                'rack_id' => '8',
                'category_id' => '19',
                'book_cover' => 'book-87.jpg',
            ],
            [
                'slug' => '88',
                'title' => '123 Pertanyaan Seputar Mpasi',
                'author' => 'Dinda Dara Saskia',
                'publisher' => 'Kawan Pustaka',
                'isbn' => '9789797578152',
                'year' => '19 Okt 2023',
                'rack_id' => '9',
                'category_id' => '19',
                'book_cover' => 'book-88.jpg',
            ],
            [
                'slug' => '89',
                'title' => 'Belajar Terampil Membuat Pola Busana',
                'author' => 'Tika Rahma F.',
                'publisher' => 'Anak Hebat Indonesia',
                'isbn' => '9786234005318',
                'year' => '29 Agt 2023',
                'rack_id' => '10',
                'category_id' => '20',
                'book_cover' => 'book-89.jpg',
            ],
            [
                'slug' => '90',
                'title' => 'Teknopreneur Aglaonema: Mengubah Hobi Menjadi Rezeki',
                'author' => 'Yuni Sugiarti',
                'publisher' => 'Gramedia Widiasarana Indonesia',
                'isbn' => '9786020528670',
                'year' => '19 Jun 2022',
                'rack_id' => '1',
                'category_id' => '20',
                'book_cover' => 'book-90.jpg',
            ],
            [
                'slug' => '91',
                'title' => 'Belajar Otodidak Membuat Pola & Menjahit Untuk Pemula',
                'author' => 'Prima Olimpiade Kristi & Nurhastuti Putri Utam',
                'publisher' => 'Pixelindo',
                'isbn' => '9786238803064',
                'year' => '24 Agt 2022',
                'rack_id' => '2',
                'category_id' => '20',
                'book_cover' => 'book-91.jpg',
            ],
            [
                'slug' => '92',
                'title' => 'Panduan Menjahit Untuk Pemula Step By Step',
                'author' => 'Khazanah El Zahra',
                'publisher' => 'Penebar Plus+',
                'isbn' => '9786237233466',
                'year' => '11 Jul 2022',
                'rack_id' => '3',
                'category_id' => '20',
                'book_cover' => 'book-92.jpg',
            ],
            [
                'slug' => '93',
                'title' => 'Mahir Menjahit: Tingkat Dasar Sampai Terampil',
                'author' => 'Hikari Luna',
                'publisher' => 'Hafamira',
                'isbn' => '9789792675351',
                'year' => '1 Mei 2015',
                'rack_id' => '4',
                'category_id' => '20',
                'book_cover' => 'book-93.jpg',
            ],
            [
                'slug' => '94',
                'title' => 'Segala Sesuatu yang Harus Anda Ketahui Tentang Diabetes',
                'author' => 'Hans Tandra',
                'publisher' => 'Gramedia Pustaka Utama',
                'isbn' => '9786020334769',
                'year' => '15 Mar 2017',
                'rack_id' => '5',
                'category_id' => '21',
                'book_cover' => 'book-94.jpg',
            ],
            [
                'slug' => '95',
                'title' => 'Peran Dokter Gigi atasi gangguan ngorok dan OSA',
                'author' => 'Prof. Drg. Laura Susanti Himawan, Sp.Pros(K), FICD',
                'publisher' => 'Penerbit Buku Kompas',
                'isbn' => '9786233467766',
                'year' => '27 Feb 2023',
                'rack_id' => '6',
                'category_id' => '21',
                'book_cover' => 'book-95.jpg',
            ],
            [
                'slug' => '96',
                'title' => '76 Ide Hidangan Nusantara untuk MPASI dan Balita',
                'author' => 'dr. Dyah Arum Kusumaningtyas',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786230045387',
                'year' => '19 Jan 2023',
                'rack_id' => '7',
                'category_id' => '21',
                'book_cover' => 'book-96.jpg',
            ],
            [
                'slug' => '97',
                'title' => 'Dari Diabetes Menuju Mata, Hati, Dan Seks',
                'author' => 'Hans Tandra',
                'publisher' => 'Gramedia Pustaka Utama',
                'isbn' => '9786020666022',
                'year' => '19 Jan 2023',
                'rack_id' => '8',
                'category_id' => '21',
                'book_cover' => 'book-97.jpg',
            ],
            [
                'slug' => '98',
                'title' => 'Bunga Rampai Berbagai Penyakit Akibat Lingkungan',
                'author' => 'Prof. Dr. dr. ANIES, M.Kes, PKK',
                'publisher' => 'Arruzz Media',
                'isbn' => '9786023136575',
                'year' => '21 Sep 2023',
                'rack_id' => '9',
                'category_id' => '21',
                'book_cover' => 'book-98.jpg',
            ],
            [
                'slug' => '99',
                'title' => 'The King`s Beast 03',
                'author' => 'Rei Toma',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786230037221',
                'year' => '30 Des 2022',
                'rack_id' => '10',
                'category_id' => '22',
                'book_cover' => 'book-99.jpg',
            ],
            [
                'slug' => '100',
                'title' => 'AKASHA : Record of Ragnarok 11',
                'author' => 'AJI Chika, Shinya UMEMURA',
                'publisher' => 'm&c!',
                'isbn' => '9786230310515',
                'year' => '28 Mar 2023',
                'rack_id' => '1',
                'category_id' => '22',
                'book_cover' => 'book-100.jpg',
            ],
            [
                'slug' => '101',
                'title' => 'AKASHA: Record of Ragnarok 09',
                'author' => 'AJI Chika, Shinya UMEMURA',
                'publisher' => 'm&c!',
                'isbn' => '9786230308079',
                'year' => '13 Sep 2022',
                'rack_id' => '2',
                'category_id' => '22',
                'book_cover' => 'book-101.jpg',
            ],
            [
                'slug' => '102',
                'title' => 'Blue Lock 12',
                'author' => 'MUNEYUKI KANESHIRO,YUSUKE NOMURA',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786230052422',
                'year' => '22 Nov 2023',
                'rack_id' => '3',
                'category_id' => '22',
                'book_cover' => 'book-102.jpg',
            ],
            [
                'slug' => '103',
                'title' => 'Komikus Shojo Nozaki 04 (Terbit Ulang)',
                'author' => 'Izumi Tsubaki',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786020270579',
                'year' => '28 Nov 2023',
                'rack_id' => '4',
                'category_id' => '22',
                'book_cover' => 'book-103.jpg',
            ],
            [
                'slug' => '104',
                'title' => 'The Guide Book Of SPSS',
                'author' => 'V. Wiratna Sujarwen, Lila Retnani Utami',
                'publisher' => 'Anak Hebat Indonesia',
                'isbn' => '9786234008937',
                'year' => '30 Agt 2023',
                'rack_id' => '5',
                'category_id' => '23',
                'book_cover' => 'book-104.jpg',
            ],
            [
                'slug' => '105',
                'title' => 'Mahir Microsoft Excel 2021',
                'author' => 'Sarwandi',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786230052330',
                'year' => '20 Nov 2023',
                'rack_id' => '6',
                'category_id' => '23',
                'book_cover' => 'book-105.jpg',
            ],
            [
                'slug' => '106',
                'title' => '36 Jam Belajar Komputer Microsoft Office 2021',
                'author' => 'Budi Permana & Kurweni Ukar',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786230033421',
                'year' => '19 Jun 2022',
                'rack_id' => '7',
                'category_id' => '23',
                'book_cover' => 'book-106.jpg',
            ],
            [
                'slug' => '107',
                'title' => 'Panduan Lengkap Menggunakan Excel 365',
                'author' => 'Yudhy Wicaksono & Solusi Kantor',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786230031960',
                'year' => '31 Mar 2022',
                'rack_id' => '8',
                'category_id' => '23',
                'book_cover' => 'book-107.jpg',
            ],
            [
                'slug' => '108',
                'title' => 'Belajar Desain 3D dengan SketchUp',
                'author' => 'Risky Budiman',
                'publisher' => 'Anak Hebat Indonesia',
                'isbn' => '9786231642844',
                'year' => '7 Nov 2023',
                'rack_id' => '9',
                'category_id' => '23',
                'book_cover' => 'book-108.jpg',
            ],
            [
                'slug' => '109',
                'title' => 'Statistika Deskriptif: untuk Ekonomi dan Bisnis',
                'author' => 'Noegroho Boedijoewono dan Tri Utomo Prasetyo',
                'publisher' => 'UPP STIM YKPN',
                'isbn' => '9786237845607',
                'year' => '10 Okt 2023',
                'rack_id' => '10',
                'category_id' => '24',
                'book_cover' => 'book-109.jpg',
            ],
            [
                'slug' => '110',
                'title' => 'Panduan Jitu Matematika SMA',
                'author' => 'Sony Adam Saputra, S.Si.',
                'publisher' => 'Anak Hebat Indonesia',
                'isbn' => '9786234004335',
                'year' => '17 Okt 2023',
                'rack_id' => '1',
                'category_id' => '24',
                'book_cover' => 'book-110.jpg',
            ],
            [
                'slug' => '111',
                'title' => 'Kalkulus Vektor',
                'author' => 'Dr. Lukman, M.Si., Endang Dedy, M.Si.',
                'publisher' => 'Bumi Aksara',
                'isbn' => '9786233286992',
                'year' => '29 Sep 2023',
                'rack_id' => '2',
                'category_id' => '24',
                'book_cover' => 'book-111.jpg',
            ],
            [
                'slug' => '112',
                'title' => 'Sistem Jam Pada Hubungan Belitan Transformator Tiga-Fasa',
                'author' => 'Prof. Marwan, S.T., M.Eng.Sc., Ph.D Dan Ir. Remigius Tandioga, M.Eng.Sc',
                'publisher' => 'Andi',
                'isbn' => '9786230127847',
                'year' => '9786230127847',
                'rack_id' => '3',
                'category_id' => '24',
                'book_cover' => 'book-112.jpg',
            ],
            [
                'slug' => '113',
                'title' => 'Poster Pintar: Pembagian',
                'author' => 'BIP',
                'publisher' => 'Bhuana Ilmu Populer',
                'isbn' => '550023152',
                'year' => '31 Jul 2023',
                'rack_id' => '4',
                'category_id' => '24',
                'book_cover' => 'book-113.jpg',
            ],
            [
                'slug' => '114',
                'title' => 'Deteksi & Diagnosis Dini Kanker',
                'author' => 'dr. Bob Andinata, Sp.B(K)Onk, dkk',
                'publisher' => 'UI PUBLISHING',
                'isbn' => '9786233331555',
                'year' => '9 Feb 2022',
                'rack_id' => '5',
                'category_id' => '25',
                'book_cover' => 'book-114.jpg',
            ],
            [
                'slug' => '115',
                'title' => 'Mims Petunjuk Konsultasi Edisi 22 Tahun 2022/2023',
                'author' => 'Medidata',
                'publisher' => 'Bhuana Ilmu Populer',
                'isbn' => '-',
                'year' => '16 Des 2022',
                'rack_id' => '6',
                'category_id' => '25',
                'book_cover' => 'book-115.jpg',
            ],
            [
                'slug' => '116',
                'title' => 'Sembuh Dan Sehat Dengan Swamedikasi (Ikhtiar Mudah Saat Sakit Dengan Obat-Obat Sederhana)',
                'author' => 'Erik Arya Tandi',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786230051104',
                'year' => '12 Nov 2023',
                'rack_id' => '7',
                'category_id' => '25',
                'book_cover' => 'book-116.jpg',
            ],
            [
                'slug' => '117',
                'title' => 'Pertolongan Pertama Untuk Setiap Orang',
                'author' => 'Juan P. Sanchez, Jr., M.D,Emelia B. Santamaria, MD',
                'publisher' => 'Gramedia Pustaka Utama',
                'isbn' => '9786020673479',
                'year' => '31 Okt 2023',
                'rack_id' => '8',
                'category_id' => '25',
                'book_cover' => 'book-117.jpg',
            ],
            [
                'slug' => '118',
                'title' => 'Mengenal Tes Buta Warna',
                'author' => 'Ns. Hamda Fikri. S,Kep.',
                'publisher' => 'Permata Press',
                'isbn' => '9786237184195',
                'year' => '22 Sep 2022',
                'rack_id' => '9',
                'category_id' => '25',
                'book_cover' => 'book-118.jpg',
            ],
            [
                'slug' => '119',
                'title' => 'Special Songs For Kids 1',
                'author' => 'Yusak Itong S.',
                'publisher' => 'Yis Production',
                'isbn' => '9790902194532',
                'year' => '8 Okt 2023',
                'rack_id' => '10',
                'category_id' => '26',
                'book_cover' => 'book-119.jpg',
            ],
            [
                'slug' => '120',
                'title' => 'Doddy Soekasah: Simfoni Alam',
                'author' => 'Bambang Supriyadi',
                'publisher' => 'Klik Plus Asia',
                'isbn' => '9786238807338',
                'year' => '30 Agt 2023',
                'rack_id' => '1',
                'category_id' => '26',
                'book_cover' => 'book-120.jpg',
            ],
            [
                'slug' => '121',
                'title' => 'Melody Pop Hits : Piano & Gitar',
                'author' => 'Eureka Julius Teruna Ryan',
                'publisher' => 'Anak Hebat Indonesia',
                'isbn' => '9790902191227',
                'year' => '5 Sep 2023',
                'rack_id' => '2',
                'category_id' => '26',
                'book_cover' => 'book-121.jpg',
            ],
            [
                'slug' => '122',
                'title' => 'Mahir Bermain Gitar Untuk Pemula: Pl Belajar Gitar Secara Otodidak',
                'author' => 'Ahmad Faisal Al Kautsar',
                'publisher' => 'Genesis Learning',
                'isbn' => '9786026475053',
                'year' => '10 Jul 2016',
                'rack_id' => '3',
                'category_id' => '26',
                'book_cover' => 'book-122.jpg',
            ],
            [
                'slug' => '123',
                'title' => 'John Lennon',
                'author' => 'Gilbert Chocky',
                'publisher' => 'Solusi Mitra Media Cv/Nusantara Cv',
                'isbn' => '9786239367848',
                'year' => '25 Apr 2021',
                'rack_id' => '4',
                'category_id' => '26',
                'book_cover' => 'book-123.jpg',
            ],
            [
                'slug' => '124',
                'title' => 'Berlatih Menulis Huruf, Kata, Kalimat, dan Angka',
                'author' => 'Annis Tsalatsa Meliana, S.Pd',
                'publisher' => 'Anak Hebat Indonesia',
                'isbn' => '9786234007848',
                'year' => '13 Nov 2023',
                'rack_id' => '5',
                'category_id' => '27',
                'book_cover' => 'book-124.jpg',
            ],
            [
                'slug' => '125',
                'title' => 'Buku Seri Ensiklopedia Lift The Flap: Antariksa',
                'author' => 'Igloobooks',
                'publisher' => 'Bhuana Ilmu Populer',
                'isbn' => '9786230407871',
                'year' => '28 Nov 2022',
                'rack_id' => '6',
                'category_id' => '27',
                'book_cover' => 'book-125.jpg',
            ],
            [
                'slug' => '126',
                'title' => 'Educomics Plants Vs Zombies: Olahraga',
                'author' => 'Xiao Jiang Nan, XIAO JIANG NAN',
                'publisher' => 'Bhuana Ilmu Populer',
                'isbn' => '9786230415906',
                'year' => '19 Nov 2023',
                'rack_id' => '7',
                'category_id' => '27',
                'book_cover' => 'book-126.jpg',
            ],
            [
                'slug' => '127',
                'title' => 'Buku Seri Pahlawan Nasional: Soekarno',
                'author' => 'WATIEK IDEO & NINDIA MAYA',
                'publisher' => 'Bhuana Ilmu Populer',
                'isbn' => '9786230414220',
                'year' => '25 Agt 2023',
                'rack_id' => '8',
                'category_id' => '27',
                'book_cover' => 'book-127.jpg',
            ],
            [
                'slug' => '128',
                'title' => 'Kumpulan Fakta Seru Sains di Sekitarmu : Seri Eksperimen Ilmiah',
                'author' => 'Kadewi, Resa Eka Ayu S., Ade Rakhma N.S.',
                'publisher' => 'Anak Hebat Indonesia',
                'isbn' => '9786025638909',
                'year' => '6 Des 2023',
                'rack_id' => '9',
                'category_id' => '27',
                'book_cover' => 'book-128.jpg',
            ],
            [
                'slug' => '129',
                'title' => 'Retail Excellence Series - What I Learned From Hypermarket Bussines',
                'author' => 'Christian F. Guswai, CHRISTIAN F. GUSWAI',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '548003278',
                'year' => '4 Des 2008',
                'rack_id' => '10',
                'category_id' => '28',
                'book_cover' => 'book-129.jpg',
            ],
            [
                'slug' => '130',
                'title' => 'Menjadi Dewasa Itu Tidak Mudah. Ya ?',
                'author' => 'Sdavincii',
                'publisher' => 'Gradien Mediatama',
                'isbn' => '9786022082491',
                'year' => '21 Mei 2023',
                'rack_id' => '1',
                'category_id' => '28',
                'book_cover' => 'book-130.jpg',
            ],
            [
                'slug' => '131',
                'title' => 'Operasi Senyap Mossad di Dunia Arab dan Iran',
                'author' => 'MUSTHAFA ABD RAHMAN',
                'publisher' => 'Penerbit Buku Kompas',
                'isbn' => '9786233467',
                'year' => '16 Mei 2023',
                'rack_id' => '2',
                'category_id' => '28',
                'book_cover' => 'book-131.jpg',
            ],
            [
                'slug' => '132',
                'title' => 'Sistem Pendidikan Finlandia: Belajar Cara Mengajar',
                'author' => 'Ratih D. Adiputri',
                'publisher' => 'Kepustakaan Populer Gramedia',
                'isbn' => '9786024819',
                'year' => '16 Mei 2023',
                'rack_id' => '3',
                'category_id' => '28',
                'book_cover' => 'book-132.jpg',
            ],
            [
                'slug' => '133',
                'title' => 'TTS Pilihan Kompas Jilid 21',
                'author' => 'Umar S H, Soepono AS, Mochammad S, Dwiweko S, Johannes A S',
                'publisher' => 'Penerbit Buku Kompas',
                'isbn' => '9786233468725',
                'year' => '13 Mei 2023',
                'rack_id' => '4',
                'category_id' => '28',
                'book_cover' => 'book-133.jpg',
            ],
            [
                'slug' => '134',
                'title' => 'Interaksi Belajar Mengajar Pendidikan Jasmani, Olahraga dan Kesehatan',
                'author' => 'Giri Wiarto, S.Pd',
                'publisher' => 'Gosyen Publishing',
                'isbn' => '9786236913291',
                'year' => '21 Nov 2023',
                'rack_id' => '5',
                'category_id' => '29',
                'book_cover' => 'book-134.jpg',
            ],
            [
                'slug' => '135',
                'title' => 'Anak Bola U-50 : Bermain Sepak Bola Diusia 50 Tahun, Kenapa Tidak ?',
                'author' => 'Alfa Febrianto',
                'publisher' => 'Litera Media',
                'isbn' => '9786236492734',
                'year' => '13 Mei 2023',
                'rack_id' => '6',
                'category_id' => '29',
                'book_cover' => 'book-135.jpg',
            ],
            [
                'slug' => '136',
                'title' => 'Aksi-Aksi Motorik Dalam Olahraga',
                'author' => 'Prof. Dr. Phil. H. Yanuar Kiram',
                'publisher' => 'Prenadamedia Group',
                'isbn' => '9786233843492',
                'year' => '31 Jan 2023',
                'rack_id' => '7',
                'category_id' => '29',
                'book_cover' => 'book-136.jpg',
            ],
            [
                'slug' => '137',
                'title' => 'Pendidikan Kesehatan Sekolah',
                'author' => 'Giri Wiarto',
                'publisher' => 'Gosyen Publishing',
                'isbn' => '9786236913222',
                'year' => '7 Jul 2022',
                'rack_id' => '8',
                'category_id' => '29',
                'book_cover' => 'book-137.jpg',
            ],
            [
                'slug' => '138',
                'title' => 'Guys Read: The Distance',
                'author' => 'Jacqueline Woodson',
                'publisher' => 'Harper Collins',
                'isbn' => 'SCOOPG86223',
                'year' => '2 Okt 2015',
                'rack_id' => '9',
                'category_id' => '29',
                'book_cover' => 'book-138.jpg',
            ],
            [
                'slug' => '139',
                'title' => 'Perencanaan Pembelajaran',
                'author' => 'Prof. Dr. T.G. Ratumanan, M.Pd. & Imas Rosmiati, S.pd., M.pd.',
                'publisher' => 'RajaGrafindo Persada',
                'isbn' => '9786230800382',
                'year' => '19 Nov 2023',
                'rack_id' => '10',
                'category_id' => '30',
                'book_cover' => 'book-139.jpg',
            ],
            [
                'slug' => '140',
                'title' => 'Insight KSN Geografi SMA',
                'author' => 'Riskiyanto, S.pd., Mpd dan Arif Nur Hidayat, S.pd., Gr.',
                'publisher' => 'Gramedia Widiasarana Indonesia',
                'isbn' => '9786020529462',
                'year' => '4 Des 2022',
                'rack_id' => '1',
                'category_id' => '30',
                'book_cover' => 'book-140.jpg',
            ],
            [
                'slug' => '141',
                'title' => 'Faster Asesmen Bahasa Indonesia untuk SD/MI Kelas 2',
                'author' => 'Tim Widya Gamma, TIM WIDYA GAMMA',
                'publisher' => 'Yrama Widya',
                'isbn' => '9786232058798',
                'year' => '27 Sep 2023',
                'rack_id' => '2',
                'category_id' => '30',
                'book_cover' => 'book-141.jpg',
            ],
            [
                'slug' => '142',
                'title' => 'Faster Asesmen Matematika untuk SD/MI Kelas 4',
                'author' => 'Tim Widya Gamma, TIM WIDYA GAMMA',
                'publisher' => 'Yrama Widya',
                'isbn' => '9786232058873',
                'year' => '27 Okt 2023',
                'rack_id' => '3',
                'category_id' => '30',
                'book_cover' => 'book-142.jpg',
            ],
            [
                'slug' => '143',
                'title' => 'Faster Asesmen Pendidikan Pancasila untuk SD/MI Kelas 5',
                'author' => 'Tim Widya Gamma, TIM WIDYA GAMMA',
                'publisher' => 'Yrama Widya',
                'isbn' => '9786232058859',
                'year' => '27 Okt 2023',
                'rack_id' => '4',
                'category_id' => '30',
                'book_cover' => 'book-143.jpg',
            ],
            [
                'slug' => '144',
                'title' => 'Hidup Seperti Kucing',
                'author' => 'Stephane Garnier',
                'publisher' => 'm&c!',
                'isbn' => '9786230311598',
                'year' => '17 Agt 2023',
                'rack_id' => '5',
                'category_id' => '31',
                'book_cover' => 'book-144.jpg',
            ],
            [
                'slug' => '145',
                'title' => 'The Principles Of Power',
                'author' => 'Dion Yulianto',
                'publisher' => 'Jendela Penerbit',
                'isbn' => '9786238847426',
                'year' => '28 Sep 2023',
                'rack_id' => '6',
                'category_id' => '31',
                'book_cover' => 'book-145.jpg',
            ],
            [
                'slug' => '146',
                'title' => 'Stolen Focus: Mengapa Perhatian Kita Mudah Teralihkan',
                'author' => 'Johann Hari',
                'publisher' => 'Gramedia Pustaka Utama',
                'isbn' => '9786020673783',
                'year' => '25 Nov 2023',
                'rack_id' => '7',
                'category_id' => '31',
                'book_cover' => 'book-146.jpg',
            ],
            [
                'slug' => '147',
                'title' => 'Journal of Joy',
                'author' => 'Sarah Amijo',
                'publisher' => 'Kepustakaan Populer Gramedia',
                'isbn' => '9786231341143',
                'year' => '21 Nov 2023',
                'rack_id' => '8',
                'category_id' => '31',
                'book_cover' => 'book-147.jpg',
            ],
            [
                'slug' => '148',
                'title' => 'The Life Journey of Kachu & Moli: The Searching of Myself',
                'author' => 'Roy Adimulyo',
                'publisher' => 'Kepustakaan Populer Gramedia',
                'isbn' => '9786231341099',
                'year' => '5 Des 2023',
                'rack_id' => '9',
                'category_id' => '31',
                'book_cover' => 'book-148.jpg',
            ],
            [
                'slug' => '149',
                'title' => 'The King TPS SNBT + B. Inggris 2024',
                'author' => 'Forum Tentor Indonesia',
                'publisher' => 'Penerbit Forum Edukasi',
                'isbn' => '9786237769576',
                'year' => '9 Agt 2023',
                'rack_id' => '10',
                'category_id' => '32',
                'book_cover' => 'book-149.jpg',
            ],
            [
                'slug' => '150',
                'title' => 'New Sukses Lolos UM UGM Soshum',
                'author' => 'TIM TENTOR MASTER GAMA',
                'publisher' => 'Kompas Ilmu',
                'isbn' => '9786023437887',
                'year' => '22 Nov 2023',
                'rack_id' => '1',
                'category_id' => '32',
                'book_cover' => 'book-150.jpg',
            ],
            [
                'slug' => '151',
                'title' => 'New Sukses Lolos UM UGM Saintek',
                'author' => 'Tim Tentor Master Gama',
                'publisher' => 'Kompas Ilmu',
                'isbn' => '9786023437870',
                'year' => '22 Nov 2023',
                'rack_id' => '2',
                'category_id' => '32',
                'book_cover' => 'book-151.jpg',
            ],
            [
                'slug' => '152',
                'title' => 'Siap IELTS Strategi Mencapai Band Score 7.0+',
                'author' => 'Nurhayati Wahyuningsih, S>S., M.Pd., & Riovanni Francinni, M.P.S.',
                'publisher' => 'Anak Hebat Indonesia',
                'isbn' => '9786231641311',
                'year' => '6 Des 2023',
                'rack_id' => '3',
                'category_id' => '32',
                'book_cover' => 'book-152.jpg',
            ],
            [
                'slug' => '153',
                'title' => 'Top High Score TOEFL Cara Jitu TOEFL 600',
                'author' => 'TIM STUDY TOEFL',
                'publisher' => 'Bintang Wahyu',
                'isbn' => '9786238181223',
                'year' => '21 Nov 2023',
                'rack_id' => '4',
                'category_id' => '32',
                'book_cover' => 'book-153.jpg',
            ],
            [
                'slug' => '154',
                'title' => 'Performance Art (dan Medan Pasca-Seni)',
                'author' => 'Afrizal Malna',
                'publisher' => 'Diva Press',
                'isbn' => '9786232937741',
                'year' => '6 Jun 2023',
                'rack_id' => '5',
                'category_id' => '33',
                'book_cover' => 'book-154.jpg',
            ],
            [
                'slug' => '155',
                'title' => 'Brilliant Book The Best Pocket Conversation',
                'author' => 'Muryani J. Semita',
                'publisher' => 'Briliant',
                'isbn' => '9786235307077',
                'year' => '29 Jul 2022',
                'rack_id' => '6',
                'category_id' => '33',
                'book_cover' => 'book-155.jpg',
            ],
            [
                'slug' => '156',
                'title' => '101 All I Wanna Do : Wanna One',
                'author' => 'Kang Jiae',
                'publisher' => 'Gramedia Widiasarana Indonesia',
                'isbn' => '9786024524586',
                'year' => '10 Des 2017',
                'rack_id' => '7',
                'category_id' => '33',
                'book_cover' => 'book-156.jpg',
            ],
            [
                'slug' => '157',
                'title' => 'Sejarah Ushul Fiqih : Histori Ilmu Ushul Fiqih Dari Masa Nabi Hingga Sekarang',
                'author' => "Prof. Dr. Ali Jum'ah",
                'publisher' => 'Keira',
                'isbn' => '9786021361979',
                'year' => '24 Nov 2017',
                'rack_id' => '8',
                'category_id' => '33',
                'book_cover' => 'book-157.jpg',
            ],
            [
                'slug' => '158',
                'title' => 'Perang-Perang Terhebat Sepanjang Sejarah',
                'author' => 'Oryza Aditama',
                'publisher' => 'Cemerlang Publishing',
                'isbn' => '9786025448058',
                'year' => '18 Nov 2017',
                'rack_id' => '9',
                'category_id' => '33',
                'book_cover' => 'book-158.jpg',
            ],
            [
                'slug' => '159',
                'title' => 'Lepas dari Pikiran Negatif dan Tekanan Batin',
                'author' => 'Dr. Ahmad Hijazi',
                'publisher' => 'Gemilang',
                'isbn' => '9786238036028',
                'year' => '28 Jan 2023',
                'rack_id' => '10',
                'category_id' => '34',
                'book_cover' => 'book-159.jpg',
            ],
            [
                'slug' => '160',
                'title' => 'Ancient Chinese Wisdom',
                'author' => 'Andri Wang',
                'publisher' => 'Gramedia Pustaka Utama',
                'isbn' => '9789792291827',
                'year' => '4 Mei 2023',
                'rack_id' => '1',
                'category_id' => '34',
                'book_cover' => 'book-160.jpg',
            ],
            [
                'slug' => '161',
                'title' => 'Nostradamus',
                'author' => 'Mario Reading',
                'publisher' => 'IIman Real',
                'isbn' => '9786029560787',
                'year' => '1 Feb 2023',
                'rack_id' => '2',
                'category_id' => '34',
                'book_cover' => 'book-161.jpg',
            ],
            [
                'slug' => '162',
                'title' => 'Power VS Force: Faktor Tersembunyi Penentu Perilaku Manusia',
                'author' => 'David R. Hawkins',
                'publisher' => 'Javanica',
                'isbn' => '9786239843861',
                'year' => '22 Nov 2023',
                'rack_id' => '3',
                'category_id' => '34',
                'book_cover' => 'book-162.jpg',
            ],
            [
                'slug' => '163',
                'title' => 'Segala-galanya Ambyar (edisi handy)',
                'author' => 'Mark Manson',
                'publisher' => 'Gramedia Widiasarana Indonesia',
                'isbn' => '9786020528557',
                'year' => '15 Mar 2022',
                'rack_id' => '4',
                'category_id' => '34',
                'book_cover' => 'book-163.jpg',
            ],
            [
                'slug' => '164',
                'title' => 'Kadang Rumah Tak Memberimu Pulang',
                'author' => 'THEORESIA RUMTHE',
                'publisher' => 'Gramedia Pustaka Utama',
                'isbn' => '9786020674506',
                'year' => '25 Nov 2023',
                'rack_id' => '5',
                'category_id' => '35',
                'book_cover' => 'book-164.jpg',
            ],
            [
                'slug' => '165',
                'title' => 'The Book of Forbidden Feelings',
                'author' => 'Lala Bohang',
                'publisher' => 'Gramedia Pustaka Utama',
                'isbn' => '9786020331898',
                'year' => '10 Jul 2016',
                'rack_id' => '6',
                'category_id' => '35',
                'book_cover' => 'book-165.jpg',
            ],
            [
                'slug' => '166',
                'title' => 'Memasihkan yang Pernah',
                'author' => 'M. Aan Mansyur',
                'publisher' => 'Shira Media',
                'isbn' => '9786027760738',
                'year' => '11 Okt 2023',
                'rack_id' => '7',
                'category_id' => '35',
                'book_cover' => 'book-166.jpg',
            ],
            [
                'slug' => '167',
                'title' => 'Masalah Tak Pernah Salah',
                'author' => 'NUGROHO PUTU',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786230050671',
                'year' => '15 Okt 2023',
                'rack_id' => '8',
                'category_id' => '35',
                'book_cover' => 'book-167.jpg',
            ],
            [
                'slug' => '168',
                'title' => 'My Coffee Affair and Other Snacks',
                'author' => 'Zulie',
                'publisher' => 'Kepustakaan Populer Gramedia',
                'isbn' => '9786024247621',
                'year' => '6 Jan 2023',
                'rack_id' => '9',
                'category_id' => '35',
                'book_cover' => 'book-168.jpg',
            ],
            [
                'slug' => '169',
                'title' => 'Buku Ensiklopedia Sains & Teknologi: Para Penemu Hebat',
                'author' => 'PARK IN-SOO',
                'publisher' => 'Bhuana Ilmu Populer',
                'isbn' => '9786230413889',
                'year' => '1 Okt 2023',
                'rack_id' => '10',
                'category_id' => '36',
                'book_cover' => 'book-169.jpg',
            ],
            [
                'slug' => '170',
                'title' => 'Ensiklopedia Negara-Negara Hebat',
                'author' => 'BEIJING YANGYANG RABBIT CULTURE',
                'publisher' => 'm&c!',
                'isbn' => '9786230309472',
                'year' => '10 Okt 2023',
                'rack_id' => '1',
                'category_id' => '36',
                'book_cover' => 'book-170.jpg',
            ],
            [
                'slug' => '171',
                'title' => 'Pedoman Komplet EYD V',
                'author' => 'Nur Indah Sholikhati, SPd., M.Pd.',
                'publisher' => 'Anak Hebat Indonesia',
                'isbn' => '9786231640437',
                'year' => '1 Okt 2023',
                'rack_id' => '2',
                'category_id' => '36',
                'book_cover' => 'book-171.jpg',
            ],
            [
                'slug' => '172',
                'title' => 'Mahir Berbahasa Indonesia',
                'author' => 'Rambu Prihatin Mega Christy',
                'publisher' => 'Anak Hebat Indonesia',
                'isbn' => '9786234009910',
                'year' => '22 Okt 2023',
                'rack_id' => '3',
                'category_id' => '36',
                'book_cover' => 'book-172.jpg',
            ],
            [
                'slug' => '173',
                'title' => 'National Geographic Faunapedia Edisi Kedua',
                'author' => 'Lucy Spelman',
                'publisher' => 'Kepustakaan Populer Gramedia',
                'isbn' => '9786231340368',
                'year' => '14 Agt 2023',
                'rack_id' => '4',
                'category_id' => '36',
                'book_cover' => 'book-173.jpg',
            ],
            [
                'slug' => '174',
                'title' => 'Teh Kekinian Untuk Usaha 75+Resep Teh Edisi Revisi',
                'author' => 'Ratna Somantri',
                'publisher' => 'Kawan Pustaka',
                'isbn' => '9789797577056',
                'year' => '1 Des 2022',
                'rack_id' => '5',
                'category_id' => '37',
                'book_cover' => 'book-174.jpg',
            ],
            [
                'slug' => '175',
                'title' => 'Resep Lengkap Jitu untuk Usaha Katering',
                'author' => 'Ayu Hartati Datmiko',
                'publisher' => 'Gramedia Pustaka Utama',
                'isbn' => '9786020662688',
                'year' => '9 Jul 2022',
                'rack_id' => '6',
                'category_id' => '37',
                'book_cover' => 'book-175.jpg',
            ],
            [
                'slug' => '176',
                'title' => 'Simple & Moist Cake (Simpel Dan Lembut Membuat Kue)',
                'author' => 'Titin Rayner',
                'publisher' => 'Kawan Pustaka',
                'isbn' => '9789797576516',
                'year' => '12 Jun 2017',
                'rack_id' => '7',
                'category_id' => '37',
                'book_cover' => 'book-176.jpg',
            ],
            [
                'slug' => '177',
                'title' => '365 Menu MPASI untuk Setahun',
                'author' => 'Fidunya Maharani Putri, A.Md.Kes.',
                'publisher' => 'Anak Hebat Indonesia',
                'isbn' => '9786234007947',
                'year' => '9 Nov 2023',
                'rack_id' => '8',
                'category_id' => '37',
                'book_cover' => 'book-177.jpg',
            ],
            [
                'slug' => '178',
                'title' => 'Sehat Lezat: Olah Saji dr. Tiwi',
                'author' => 'I Gusti Ayu Nyoman Partiwi (dr. Tiwi)',
                'publisher' => 'Buku Kompas',
                'isbn' => '9786024123833',
                'year' => '2 Feb 2021',
                'rack_id' => '9',
                'category_id' => '37',
                'book_cover' => 'book-178.jpg',
            ],
            [
                'slug' => '179',
                'title' => 'Inspirasi Feng Shui: Buang - Pindah - Tambah',
                'author' => 'Dewi Mariana',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786230037306',
                'year' => '30 Des 2022',
                'rack_id' => '10',
                'category_id' => '38',
                'book_cover' => 'book-179.jpg',
            ],
            [
                'slug' => '180',
                'title' => '24 Desain Rumah < 90 Juta',
                'author' => 'Dmaximus Arc',
                'publisher' => 'Griya Kreasi',
                'isbn' => '9786026564924',
                'year' => '2 Mar 2023',
                'rack_id' => '1',
                'category_id' => '38',
                'book_cover' => 'book-180.jpg',
            ],
            [
                'slug' => '181',
                'title' => 'Panduan Lengkap Menghitung Biaya Membangun Rumah',
                'author' => 'Ir. Gatut Susanta',
                'publisher' => 'Pt. Niaga Swadaya',
                'isbn' => '9786026564580',
                'year' => '1 Des 2021',
                'rack_id' => '2',
                'category_id' => '38',
                'book_cover' => 'book-181.jpg',
            ],
            [
                'slug' => '182',
                'title' => 'Mahir Menjahit: Tingkat Dasar Sampai Terampil',
                'author' => 'Hikari Luna',
                'publisher' => 'Hafamira',
                'isbn' => '9789792675351',
                'year' => '1 Mei 2015',
                'rack_id' => '3',
                'category_id' => '38',
                'book_cover' => 'book-182.jpg',
            ],
            [
                'slug' => '183',
                'title' => 'Kompilasi Hukum Islam (KHI) Edisi Lengkap',
                'author' => 'Tim Redaksi Nuansa Aulia',
                'publisher' => 'Nuansa Aulia',
                'isbn' => '9789790713413',
                'year' => '17 Agt 2020',
                'rack_id' => '4',
                'category_id' => '38',
                'book_cover' => 'book-183.jpg',
            ],
            [
                'slug' => '184',
                'title' => 'Panduan Jitu Fisika Sma',
                'author' => 'Sony Adam Saputra, S.Si.',
                'publisher' => 'Anak Hebat Indonesia',
                'isbn' => '9786231641076',
                'year' => '20 Sep 2023',
                'rack_id' => '5',
                'category_id' => '39',
                'book_cover' => 'book-184.jpg',
            ],
            [
                'slug' => '185',
                'title' => 'Panduan Jitu Kimia SMA',
                'author' => 'Sony Adam Saputra, S.Si.',
                'publisher' => 'Anak Hebat Indonesia',
                'isbn' => '9786234004328',
                'year' => '11 Okt 2023',
                'rack_id' => '6',
                'category_id' => '39',
                'book_cover' => 'book-185.jpg',
            ],
            [
                'slug' => '186',
                'title' => 'Buku Ajar Biologi Kedokteran',
                'author' => 'Hebert Adrianto',
                'publisher' => 'Andi',
                'isbn' => '9786236822661',
                'year' => '13 Sep 2023',
                'rack_id' => '7',
                'category_id' => '39',
                'book_cover' => 'book-186.jpg',
            ],
            [
                'slug' => '187',
                'title' => 'Pengembangan Kurikulum dan Sumber Belajar Geografi',
                'author' => 'Prof. Muhammad Zid, M.Si. Dr. Oot Hotimah, S.Pd., M.Si.',
                'publisher' => 'Bumi Aksara',
                'isbn' => '9786233287074',
                'year' => '29 Agt 2023',
                'rack_id' => '8',
                'category_id' => '39',
                'book_cover' => 'book-187.jpg',
            ],
            [
                'slug' => '188',
                'title' => 'Sukacita Sains',
                'author' => 'Jim al-Khalili',
                'publisher' => 'Kepustakaan Populer Gramedia',
                'isbn' => '9786231340764',
                'year' => '19 Sep 2023',
                'rack_id' => '9',
                'category_id' => '39',
                'book_cover' => 'book-188.jpg',
            ],
            [
                'slug' => '189',
                'title' => 'Karsa & Karya Demi Kemanusiaan',
                'author' => 'RAVANDO',
                'publisher' => 'Penerbit Buku Kompas',
                'isbn' => '9786231602206',
                'year' => '22 Nov 2023',
                'rack_id' => '10',
                'category_id' => '40',
                'book_cover' => 'book-189.jpg',
            ],
            [
                'slug' => '190',
                'title' => 'Kisah Saranjana: Kota Gaib Kalimantan',
                'author' => 'Diki Rifattama',
                'publisher' => 'cakrawala media pustaka',
                'isbn' => '9786239603298',
                'year' => '2 Nov 2023',
                'rack_id' => '1',
                'category_id' => '40',
                'book_cover' => 'book-190.jpg',
            ],
            [
                'slug' => '191',
                'title' => 'Hitam Putih Majapahit',
                'author' => 'Muhammad Muhlisin',
                'publisher' => 'Araska Publishing',
                'isbn' => '9786236335284',
                'year' => '27 Agt 2023',
                'rack_id' => '2',
                'category_id' => '40',
                'book_cover' => 'book-191.jpg',
            ],
            [
                'slug' => '192',
                'title' => 'Melewati Batas',
                'author' => 'Tim Penulis ODGOI',
                'publisher' => 'Yayasan Pustaka Obor Indonesia',
                'isbn' => '9786233212274',
                'year' => '14 Agt 2023',
                'rack_id' => '3',
                'category_id' => '40',
                'book_cover' => 'book-192.jpg',
            ],
            [
                'slug' => '193',
                'title' => 'Merdeka',
                'author' => 'Harry Poeze dan Henk Schulte Nordholt',
                'publisher' => 'Yayasan Pustaka Obor Indonesia',
                'isbn' => '9786233212359',
                'year' => '14 Sep 2023',
                'rack_id' => '4',
                'category_id' => '40',
                'book_cover' => 'book-193.jpg',
            ],
            [
                'slug' => '194',
                'title' => 'Menua dengan Gembira',
                'author' => 'Andina Dwifatma',
                'publisher' => 'shira media',
                'isbn' => '9786027790707',
                'year' => '11 Jul 2023',
                'rack_id' => '5',
                'category_id' => '41',
                'book_cover' => 'book-194.jpg',
            ],
            [
                'slug' => '195',
                'title' => 'Read, Life, Love',
                'author' => 'Pongki Pamungkas',
                'publisher' => 'Kepustakaan Populer Gramedia',
                'isbn' => '9786231340399',
                'year' => '25 Jul 2023',
                'rack_id' => '6',
                'category_id' => '41',
                'book_cover' => 'book-195.jpg',
            ],
            [
                'slug' => '196',
                'title' => 'Metodologi Penelitian Bahasa Rupa',
                'author' => 'Riza Istanto',
                'publisher' => 'Thafa Media',
                'isbn' => '9786025589638',
                'year' => '21 Nov 2022',
                'rack_id' => '7',
                'category_id' => '41',
                'book_cover' => 'book-196.jpg',
            ],
            [
                'slug' => '197',
                'title' => 'My Imagination :Terapi Warna Untuk Melepas Stres',
                'author' => 'Arelita, Emha Ainun Najib, Linda Apriani',
                'publisher' => 'Kawan Pustaka',
                'isbn' => '9789797576370',
                'year' => '9 Nov 2015',
                'rack_id' => '8',
                'category_id' => '41',
                'book_cover' => 'book-197.jpg',
            ],
            [
                'slug' => '198',
                'title' => 'Bahasa Polandia untuk Pemula',
                'author' => 'Arun Śmieszek dan Piotr Śmieszek',
                'publisher' => 'Gramedia Pustaka Utama',
                'isbn' => '9786020673684',
                'year' => '14 Nov 2023',
                'rack_id' => '9',
                'category_id' => '42',
                'book_cover' => 'book-198.jpg',
            ],
            [
                'slug' => '199',
                'title' => 'Korean Vocabulary for Daily Conversation',
                'author' => 'Danu Suprobo & Riswari Afifah',
                'publisher' => 'Genta Group',
                'isbn' => '978623252285',
                'year' => '22 Nov 2023',
                'rack_id' => '10',
                'category_id' => '42',
                'book_cover' => 'book-199.jpg',
            ],
            [
                'slug' => '200',
                'title' => 'Latihan Menulis Kanji N5',
                'author' => 'Iqrodatul M.U.Z.',
                'publisher' => 'Anak Hebat Indonesia',
                'isbn' => '9786231641410',
                'year' => '6 Nov 2023',
                'rack_id' => '1',
                'category_id' => '42',
                'book_cover' => 'book-200.jpg',
            ],
            [
                'slug' => '201',
                'title' => 'Fun English Learning: About Me And Things Around',
                'author' => 'YULI KISMAWATI, S.PD.,VERONICA WINATA',
                'publisher' => 'Elex Media Komputindo',
                'isbn' => '9786230050961',
                'year' => '6 Nov 2023',
                'rack_id' => '2',
                'category_id' => '42',
                'book_cover' => 'book-201.jpg',
            ],
            [
                'slug' => '202',
                'title' => 'Grand Master Of English Grammar Tenses & Vocabulary',
                'author' => 'English Tutor Association Team',
                'publisher' => 'Edu Penguin',
                'isbn' => '9786023438044',
                'year' => '24 Okt 2023',
                'rack_id' => '3',
                'category_id' => '42',
                'book_cover' => 'book-202.jpg',
            ],
            [
                'slug' => '203',
                'title' => 'Indistractable',
                'author' => 'Nir Eyal',
                'publisher' => 'Renebook',
                'isbn' => '9786236083604',
                'year' => '15 Okt 2023',
                'rack_id' => '4',
                'category_id' => '43',
                'book_cover' => 'book-203.jpg',
            ],
            [
                'slug' => '204',
                'title' => 'Pocket Oxford Dictionary & Thesaurus',
                'author' => 'Oxford Dictionaries',
                'publisher' => 'Sinar Star Book',
                'isbn' => '9780199532865',
                'year' => '5 Feb 2008',
                'rack_id' => '5',
                'category_id' => '43',
                'book_cover' => 'book-204.jpg',
            ],
            [
                'slug' => '205',
                'title' => 'Teladan Dari Tiongkok',
                'author' => 'Dahlan Iskan',
                'publisher' => 'Pustaka Obor Indonesia',
                'isbn' => '9786236421611',
                'year' => '16 Jul 2023',
                'rack_id' => '6',
                'category_id' => '43',
                'book_cover' => 'book-205.jpg',
            ],
            [
                'slug' => '206',
                'title' => 'Jurnal Harga Satuan Bahan Bangunan Konstruksi & Interior Edisi 42 Tahun 2023',
                'author' => 'Rambang Basari',
                'publisher' => 'Jurnal / Yys Pandu Bangun P Nust',
                'isbn' => '08534829',
                'year' => '16 Jul 2023',
                'rack_id' => '7',
                'category_id' => '43',
                'book_cover' => 'book-206.jpg',
            ],
            [
                'slug' => '207',
                'title' => 'Panduan Resmi Tes Seleksi Masuk TNI-POLRI 2023/2024',
                'author' => 'Praja Edukasi',
                'publisher' => 'Bintang Wahyu',
                'isbn' => '9786026320995',
                'year' => '21 Mei 2023',
                'rack_id' => '8',
                'category_id' => '43',
                'book_cover' => 'book-207.jpg',
            ],
            [
                'slug' => '208',
                'title' => 'Pandai Mengenal Transportasi Masa Depan',
                'author' => 'Arinda Cahya Wulandari',
                'publisher' => 'Anak Hebat Indonesia',
                'isbn' => '9786234006872',
                'year' => '17 Okt 2023',
                'rack_id' => '9',
                'category_id' => '44',
                'book_cover' => 'book-208.jpg',
            ],
            [
                'slug' => '209',
                'title' => 'Reparasi Dan Over Haul Kelistrikan Mesin Mobil',
                'author' => 'Drs. Daryanto',
                'publisher' => 'Bumi Aksara',
                'isbn' => '9786233286831',
                'year' => '29 Jun 2023',
                'rack_id' => '10',
                'category_id' => '44',
                'book_cover' => 'book-209.jpg',
            ],
            [
                'slug' => '210',
                'title' => 'Panduan Praktis Servis Sistem Chassis Sepeda Motor',
                'author' => 'Drs. Buntarto, M.Pd.',
                'publisher' => 'Pustaka Baru Press',
                'isbn' => '9786020874067',
                'year' => '26 Mar 2017',
                'rack_id' => '1',
                'category_id' => '44',
                'book_cover' => 'book-210.jpg',
            ],
            [
                'slug' => '211',
                'title' => 'Hari-Hari di Bloomsbury: Petualangan #Studentjouralist di London, Inggris',
                'author' => 'Denty Piawai Nastitie',
                'publisher' => 'Penerbit Buku Kompas',
                'isbn' => '9786231602138',
                'year' => '28 Nov 2023',
                'rack_id' => '2',
                'category_id' => '45',
                'book_cover' => 'book-211.jpg',
            ],
            [
                'slug' => '212',
                'title' => 'New Update Atlas Pelajar Superlengkap Indonesia & Dunia',
                'author' => 'Sev Sukandar',
                'publisher' => 'B-media',
                'isbn' => '9786026725837',
                'year' => '16 Okt 2023',
                'rack_id' => '3',
                'category_id' => '45',
                'book_cover' => 'book-212.jpg',
            ],
            [
                'slug' => '213',
                'title' => 'Atlas Negeriku Indonesia Disertai Asean 38 Provinsi Di Indonesia',
                'author' => 'Tim Redaksi',
                'publisher' => 'pustaka baru press',
                'isbn' => '9786023768868',
                'year' => '13 Sep 2023',
                'rack_id' => '4',
                'category_id' => '45',
                'book_cover' => 'book-213.jpg',
            ],
            [
                'slug' => '214',
                'title' => 'Atlas Indonesia & Dunia 38 Provinsi Edisi Terbaru',
                'author' => 'TIM PENYUSUN',
                'publisher' => 'Pustaka Agung Harapan',
                'isbn' => '9786023768837',
                'year' => '8 Sep 2023',
                'rack_id' => '5',
                'category_id' => '45',
                'book_cover' => 'book-214.jpg',
            ],
            [
                'slug' => '215',
                'title' => 'Atlas Geografi Indonesia Dan Dunia',
                'author' => 'Tim Bip',
                'publisher' => 'Bhuana Ilmu Populer',
                'isbn' => '9786023940776',
                'year' => '19 Jun 2016',
                'rack_id' => '6',
                'category_id' => '45',
                'book_cover' => 'book-215.jpg',
            ],
            [
                'slug' => '216',
                'title' => 'The Nerror Vault : Conspiracy',
                'author' => 'Nessie Judge',
                'publisher' => 'Bukune',
                'isbn' => '9786022206545',
                'year' => '30 Okt 2023',
                'rack_id' => '7',
                'category_id' => '46',
                'book_cover' => 'book-216.jpg',
            ],
            [
                'slug' => '217',
                'title' => 'Everyday in My Life',
                'author' => 'Farahasyahidah',
                'publisher' => 'Laksana',
                'isbn' => '9786233274814',
                'year' => '19 Okt 2023',
                'rack_id' => '8',
                'category_id' => '46',
                'book_cover' => 'book-217.jpg',
            ],
            [
                'slug' => '218',
                'title' => 'Seni Menciptakan Kedamaian dalam Diri',
                'author' => 'Dewi Indra Puspitasari',
                'publisher' => 'Anak Hebat Indonesia',
                'isbn' => '9786234006551',
                'year' => '25 Jul 2023',
                'rack_id' => '9',
                'category_id' => '46',
                'book_cover' => 'book-218.jpg',
            ],
            [
                'slug' => '219',
                'title' => "Notice What You're Noticing",
                'author' => 'Meina Tan',
                'publisher' => 'Brilliant Books',
                'isbn' => '9786235307336',
                'year' => '28 Jul 2023',
                'rack_id' => '10',
                'category_id' => '46',
                'book_cover' => 'book-219.jpg',
            ],
            [
                'slug' => '220',
                'title' => 'Hipnopresur Kombinasi Hipnosis & Akupresur',
                'author' => 'M Ferry Wong',
                'publisher' => 'Penebar Plus+',
                'isbn' => '9786237233626',
                'year' => '14 Jun 2023',
                'rack_id' => '1',
                'category_id' => '46',
                'book_cover' => 'book-220.jpg',
            ],
        ];
        foreach ($data as $book){
            $bookModel->insert($book);
        }
    }

}