<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class LoanSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'id' => 1,
                'book_id' => 108,
                'quantity' => 1,
                'member_id' => 1,
                'uid' => sha1('1'),
                'loan_date' => '2023-11-21',
                'due_date' => '2023-11-28',
                'return_date' => null,
            ],
            [
                'id' => 2,
                'book_id' => 199,
                'quantity' => 1,
                'member_id' => 2,
                'uid' => sha1('2'),
                'loan_date' => '2023-11-13',
                'due_date' => '2023-11-20',
                'return_date' => null,
            ],
            [
                'id' => 3,
                'book_id' => 11,
                'quantity' => 5,
                'member_id' => 3,
                'uid' => sha1('3'),
                'loan_date' => '2023-11-13',
                'due_date' => '2023-11-20',
                'return_date' => '2023-11-24',
            ],
            [
                'id' => 4,
                'book_id' => 103,
                'quantity' => 1,
                'member_id' => 4,
                'uid' => sha1('4'),
                'loan_date' => '2023-11-7',
                'due_date' => '2023-11-21',
                'return_date' => '2023-11-24',
            ],
            [
                'id' => 5,
                'book_id' => 103,
                'quantity' => 1,
                'member_id' => 5,
                'uid' => sha1('5'),
                'loan_date' => '2023-11-7',
                'due_date' => '2023-11-21',
                'return_date' => null,
            ],
            [
                'id' => 6,
                'book_id' => 103,
                'quantity' => 1,
                'member_id' => 6,
                'uid' => sha1('6'),
                'loan_date' => '2023-11-7',
                'due_date' => '2023-11-21',
                'return_date' => null,
            ],
            [
                'id' => 7,
                'book_id' => 103,
                'quantity' => 1,
                'member_id' => 7,
                'uid' => sha1('7'),
                'loan_date' => '2023-11-7',
                'due_date' => '2023-11-21',
                'return_date' => null,
            ],
            [
                'id' => 8,
                'book_id' => 103,
                'quantity' => 1,
                'member_id' => 8,
                'uid' => sha1('8'),
                'loan_date' => '2023-11-7',
                'due_date' => '2023-11-21',
                'return_date' => null,
            ],
            [
                'id' => 9,
                'book_id' => 103,
                'quantity' => 1,
                'member_id' => 9,
                'uid' => sha1('9'),
                'loan_date' => '2023-11-7',
                'due_date' => '2023-11-21',
                'return_date' => null,
            ],
            [
                'id' => 10,
                'book_id' => 103,
                'quantity' => 1,
                'member_id' => 10,
                'uid' => sha1('10'),
                'loan_date' => '2023-11-7',
                'due_date' => '2023-11-21',
                'return_date' => null,
            ],
            [
                'id' => 11,
                'book_id' => 103,
                'quantity' => 1,
                'member_id' => 11,
                'uid' => sha1('11'),
                'loan_date' => '2023-11-7',
                'due_date' => '2023-11-21',
                'return_date' => null,
            ],
            [
                'id' => 12,
                'book_id' => 103,
                'quantity' => 1,
                'member_id' => 12,
                'uid' => sha1('12'),
                'loan_date' => '2023-11-7',
                'due_date' => '2023-11-21',
                'return_date' => null,
            ],
            [
                'id' => 13,
                'book_id' => 103,
                'quantity' => 1,
                'member_id' => 13,
                'uid' => sha1('13'),
                'loan_date' => '2023-11-7',
                'due_date' => '2023-11-21',
                'return_date' => null,
            ],
            [
                'id' => 14,
                'book_id' => 103,
                'quantity' => 1,
                'member_id' => 14,
                'uid' => sha1('14'),
                'loan_date' => '2023-11-7',
                'due_date' => '2023-11-21',
                'return_date' => null,
            ],
            [
                'id' => 15,
                'book_id' => 103,
                'quantity' => 1,
                'member_id' => 15,
                'uid' => sha1('15'),
                'loan_date' => '2023-11-7',
                'due_date' => '2023-11-21',
                'return_date' => null,
            ],
            [
                'id' => 16,
                'book_id' => 103,
                'quantity' => 1,
                'member_id' => 16,
                'uid' => sha1('16'),
                'loan_date' => '2023-11-7',
                'due_date' => '2023-11-21',
                'return_date' => null,
            ],
            [
                'id' => 17,
                'book_id' => 103,
                'quantity' => 1,
                'member_id' => 17,
                'uid' => sha1('17'),
                'loan_date' => '2023-11-7',
                'due_date' => '2023-11-21',
                'return_date' => null,
            ],
        ];

        $this->db->table('loans')->insertBatch($data);

        $this->call('FineSeeder');
    }
}
